version: '3.8'
services:
  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    ports:
      - '8086:8086'
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: 'setup'
      DOCKER_INFLUXDB_INIT_USERNAME: 'admin'
      DOCKER_INFLUXDB_INIT_PASSWORD: ${DOCKER_INFLUXDB_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: 'iot-g3'
      DOCKER_INFLUXDB_INIT_BUCKET: 'iaq-data'
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: '${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}'

  nodered:
    build: .
    image: nodered-image
    container_name: nodered
    ports:
      - '1880:1880'
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - node-red-data:/data
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-configs:/etc/grafana/provisioning
      - ./IoT_BG.png:/usr/share/grafana/public/img/bg/IoT_BG.png
    environment:
      GF_RENDERING_SERVER_URL: http://grafana-image-renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    depends_on:
      - influxdb

  grafana-image-renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - "8081:8081"
  grafana-reporter:
    image: izakmarais/grafana-reporter:${gr_version:-latest}
    command: "-ip grafana:3000"
    ports:
      - "8686:8686"

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    restart: unless-stopped

volumes:
  influxdb-data:
  node-red-data:
  grafana-data:
  mosquitto-data:
  mosquitto-log:
