{
 "title": "Analytics Dashboard (Single Sensor)",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device_names",
    "label": "Device Name",
    "query": "import \"influxdata/influxdb/v1\" v1.tagValues(bucket: \"iaq-data\", tag: \"deviceName\")\r\n\r\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 21, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iaq-data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iaq-data\")\r\n  |> filter(fn: (r) => r[\"deviceName\"] == \"${device_names}\")\r\n  |> map(fn: (r) => ({r with _value: float(v: r._value)}))\r\n  |> aggregateWindow(every: 10m, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iaq-data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iaq-data\")\r\n  |> filter(fn: (r) => r[\"deviceName\"] == \"${device_names}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> map(fn: (r) => ({r with _value: float(v: r._value)}))\r\n  |> aggregateWindow(every: 10m, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"iaq-data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iaq-data\")\r\n  |> filter(fn: (r) => r[\"deviceName\"] == \"${device_names}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> map(fn: (r) => ({r with _value: float(v: r._value)}))\r\n  |> aggregateWindow(every: 10m, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Carbon Dioxide",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"iaq-data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iaq-data\")\r\n  |> filter(fn: (r) => r[\"deviceName\"] == \"${device_names}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carbon dioxide\")\r\n  |> map(fn: (r) => ({r with _value: float(v: r._value)}))\r\n  |> aggregateWindow(every: 10m, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  }
 ]
}