{
 "title": "Analytics Dashboard (All Sensors)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"iaq-data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iaq-data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> map(fn: (r) => ({\n      r with _value: float(v: r._value),\n      _field: r[\"device_name\"]\n  }))\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"iaq-data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iaq-data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |> map(fn: (r) => ({\n      r with _value: float(v: r._value),\n      _field: r[\"device_name\"]\n  }))\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Carbon Dioxide",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"iaq-data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iaq-data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"carbon dioxide\")\n  |> map(fn: (r) => ({\n      r with _value: float(v: r._value),\n      _field: r[\"device_name\"]\n  }))\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}