{
 "title": "IAQ Report Dashboard",
 "description": "Executive reports of air quality trends",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Monthly CO2 Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"iaq-data\")\r\n  |> range(start: -30d, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iaq-data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carbon dioxide\")\r\n  |> group(columns: [\"_measurement\", \"_start\", \"_stop\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Highest recorded CO2 (30 Days)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"iaq-data\")\r\n  |> range(start: -30d, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iaq-data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carbon dioxide\")\r\n  |> filter(fn: (r) => r[\"deviceName\"] == \"AM319-Sensor_1\" or r[\"deviceName\"] == \"AM307-Sensor_2\" or r[\"deviceName\"] == \"AM319-Sensor_3\" or r[\"deviceName\"] == \"AM103-Sensor_4\" or r[\"deviceName\"] == \"AM103L-Sensor_5\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> top(n: 1)\r\n  |> map(fn: (r) => ({\r\n      deviceName: r.deviceName,\r\n      _value: r._value,\r\n      _time: r._time\r\n      \r\n  }))\r\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Monthly Temperature Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"iaq-data\")\r\n  |> range(start: -30d, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iaq-data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> group(columns: [\"_measurement\", \"_start\", \"_stop\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Highest recorded Temperature (30 Days)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"iaq-data\")\r\n  |> range(start: -30d, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iaq-data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"deviceName\"] == \"AM319-Sensor_1\" or r[\"deviceName\"] == \"AM307-Sensor_2\" or r[\"deviceName\"] == \"AM319-Sensor_3\" or r[\"deviceName\"] == \"AM103-Sensor_4\" or r[\"deviceName\"] == \"AM103L-Sensor_5\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> top(n: 1)\r\n  |> map(fn: (r) => ({\r\n      deviceName: r.deviceName,\r\n      _value: r._value,\r\n      _time: r._time\r\n      \r\n  }))\r\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Monthly Humidity Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"iaq-data\")\r\n  |> range(start: -30d, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iaq-data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> group(columns: [\"_measurement\", \"_start\", \"_stop\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Highest recorded Humidity (30 Days)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"iaq-data\")\r\n  |> range(start: -30d, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iaq-data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> filter(fn: (r) => r[\"deviceName\"] == \"AM319-Sensor_1\" or r[\"deviceName\"] == \"AM307-Sensor_2\" or r[\"deviceName\"] == \"AM319-Sensor_3\" or r[\"deviceName\"] == \"AM103-Sensor_4\" or r[\"deviceName\"] == \"AM103L-Sensor_5\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> top(n: 1)\r\n  |> map(fn: (r) => ({\r\n      deviceName: r.deviceName,\r\n      _value: r._value,\r\n      _time: r._time\r\n      \r\n  }))\r\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Sensor locations",
   "type": "canvas",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  }
 ]
}